# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yTmW2aQswPRS-V2WK1Vqrx8qi8X5207Y
"""

import streamlit as st
import fastf1
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

import tempfile
cache_dir = tempfile.mkdtemp()
fastf1.Cache.enable_cache(cache_dir)


st.title("2025 Las Vegas GP – F1 Data Dashboard")

# Sidebar inputs
year = 2025
gp = "Las Vegas"
session_type = "R"

session = fastf1.get_session(year, gp, session_type)
session.load()

st.sidebar.success("Session Loaded Successfully")

# Select Driver
drivers = sorted(session.laps['Driver'].unique())
driver1 = st.sidebar.selectbox("Driver 1", drivers)
driver2 = st.sidebar.selectbox("Driver 2", drivers)

laps = session.laps.copy()

# ---------------------
# PIT STOP TABLE
# ---------------------
st.header("📌 Pit Stop Summary")

pit_stops = laps.loc[laps['PitInTime'].notna()]
pit_stops_display = pit_stops[['Driver','LapNumber','Stint','PitInTime','PitOutTime',
                               'Compound','TyreLife','FreshTyre']]
st.dataframe(pit_stops_display.sort_values(by=['Driver','LapNumber']))


# ---------------------
# SECTOR TIMES TABLE
# ---------------------
st.header("⏱ Sector Times")
sector_times = laps[['Driver','LapNumber','Sector1Time','Sector2Time','Sector3Time']]
sector_times = sector_times.dropna()
st.dataframe(sector_times)


# ---------------------
# LAP TIME TREND
# ---------------------
st.header("📈 Lap Time Trend (All Drivers)")
laps_clean = laps.dropna(subset=['LapTime'])
laps_clean['LapTime (s)'] = laps_clean['LapTime'].dt.total_seconds()

fig = px.line(
    laps_clean,
    x="LapNumber",
    y="LapTime (s)",
    color="Driver",
    title="Lap Time Trend"
)
st.plotly_chart(fig)


# -------------------------
# SPEED TRACE COMPARISON
# -------------------------
st.header("🚀 Speed Trace Comparison")

lap1 = session.laps.pick_driver(driver1).pick_fastest()
lap2 = session.laps.pick_driver(driver2).pick_fastest()

tel1 = lap1.get_car_data().add_distance()
tel2 = lap2.get_car_data().add_distance()

fig2, ax2 = plt.subplots(figsize=(10, 5))
ax2.plot(tel1['Distance'], tel1['Speed'], label=driver1)
ax2.plot(tel2['Distance'], tel2['Speed'], label=driver2)
ax2.set_xlabel("Distance (m)")
ax2.set_ylabel("Speed (km/h)")
ax2.legend()
st.pyplot(fig2)


# ---------------------
# STINT / TYRE STRATEGY
# ---------------------
st.header("🛞 Tyre Stint Strategy")

fig3, ax3 = plt.subplots(figsize=(10, 6))

drivers_list = pd.unique(laps['Driver'])

for d in drivers_list:
    d_laps = laps.loc[laps['Driver'] == d]

    for stint_num in d_laps['Stint'].unique():
        s_laps = d_laps[d_laps['Stint'] == stint_num]

        start = s_laps['LapNumber'].min()
        end = s_laps['LapNumber'].max()
        compound = s_laps['Compound'].iloc[0]

        color = {
            "SOFT": "red",
            "MEDIUM": "yellow",
            "HARD": "white"
        }.get(compound, "gray")

        ax3.barh(d, end - start, left=start, color=color, edgecolor="black")

ax3.set_xlabel("Lap Number")
ax3.set_ylabel("Driver")
ax3.set_title("Stint Strategy")
st.pyplot(fig3)
